---
name: Super-Linter

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    # checkov:skip=CKV2_GHA_1 "Permissions are already minimal(contents: read, statuses: write)"
    permissions:
      contents: read
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v4
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0
          persist-credentials: false

      - name: Run Linter
        uses: super-linter/super-linter@2bdd90ed3262e023ac84bf8fe35dc480721fc1f2 #v8.2.1
        env:
          VALIDATE_MARKDOWN: false
          VALIDATE_BIOME_FORMAT: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
